site_name: Fortify DevOps Guide
base_url: /fortify-dev-guide
repo_url: https://github.com/treisland/fortify_docs_mkdocs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  font:
    text: Poppins
  logo: assets/cyberres-opentext.png
  favicon: assets/logo-fortify.png
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      title: Table Of Contents

plugins:
  - glightbox
  - macros
  - mkdocs-video
  - search
nav:
  - Home: index.md
  - Platform: 'platform_tools/index.md'
  - Integrations: 
    - 'integrations/index.md'
    - IDE:
      - Android Studio: 'integrations/androidstudio.md'
      - Eclipse: 'integrations/eclipse.md'
      - IntelliJ: 'integrations/intellij.md'
      - Visual Studio: 'integrations/visualstudio.md'
      - Visual Studio Code: 'integrations/vscode.md'
    - CI/CD:
      - Azure DevOps: 'integrations/azuredevops.md'
      - Github: 'integrations/github.md'
      - Gitlab: 'integrations/gitlab.md'
      - Jenkins: 'integrations/jenkins.md'
    - BugTracking:
      - Jira: 'integrations/jira.md'
    
  - Resources: 'resources.md'
  - Announcements: 'https://community.microfocus.com/cyberres/fortify/w/fortify-product-announcements'