name: build 
on:
  workflow_dispatch:
  pull_request:
    branches:
      main
env:
  REPO_NAME: ${{ vars.REPO_NAME }}
  REPO_URL: ${{ vars.REPO_URL}}

  SITE_NAME: ${{ vars.SITE_NAME }}
  SITE_URL: ${{ vars.SITE_URL }}

permissions:
  contents: write
jobs:
  pip_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: MKDocs Build
        run: mkdocs build --clean
