name: deploy

env:
  DOC_VERSION: "0.1.3"

on:
  workflow_dispatch:
  push:
    branches: 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: |
          git config user.name mkdocs-bot
          git config user.email mkdocs-bot@example.com
          git fetch origin gh-pages --depth=1
          mike set-default latest
          mike deploy ${{ env.DOC_VERSION }} latest --push -u
